"""Unit tests for the BMP protocol parser."""
import struct

import pytest

from core.bmp_parser import BMPParser, MSG_ROUTE_MONITORING
from tests.fixtures.bgp_telemetry_generator import MockBGPTelemetryGenerator


@pytest.fixture
def gen():
    return MockBGPTelemetryGenerator(num_speakers=2, prefixes_per_speaker=10)


@pytest.fixture
def parser():
    return BMPParser()


class TestBMPCommonHeader:
    def test_parse_valid_header(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001)
        header = parser._parse_common_header(bmp)
        assert header.version == 3
        assert header.message_length == len(bmp)
        assert header.message_type == MSG_ROUTE_MONITORING

    def test_rejects_wrong_version(self, parser):
        bad = bytes([2, 0, 0, 0, 6, 0])
        with pytest.raises(ValueError, match="version"):
            parser._parse_common_header(bad)

    def test_rejects_too_short_data(self, parser):
        with pytest.raises(ValueError):
            parser._parse_common_header(b"\x03\x00")


class TestBMPPerPeerHeader:
    def test_parse_ipv4_peer(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001)
        peer, offset = parser._parse_per_peer_header(bmp, offset=6)
        assert peer.peer_asn == 65001
        assert peer.is_ipv6 is False
        assert offset == 48

    def test_ipv6_flag_detected(self, parser):
        # Build minimal 42-byte header with V flag set
        peer_addr = b"\x00" * 16
        header = struct.pack(
            ">BB8s16sI4sII",
            0,
            0x80,  # V flag
            b"\x00" * 8,
            peer_addr,
            65001,
            b"\x7f\x00\x00\x01",
            1000,
            0,
        )
        peer, _ = parser._parse_per_peer_header(header, offset=0)
        assert peer.is_ipv6 is True

    def test_timestamp_extracted(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001)
        peer, _ = parser._parse_per_peer_header(bmp, offset=6)
        assert peer.timestamp_seconds > 0


class TestBGPUpdateParsing:
    def test_parse_route_update(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001, as_path=[65001, 65002, 65003])
        result = parser.parse_message(bmp)
        body = result["body"]
        assert "10.0.0.0/24" in body.nlri_prefixes
        assert body.path_attributes["as_path"] == [65001, 65002, 65003]

    def test_parse_route_withdraw(self, gen, parser):
        bmp = gen.generate_withdraw("192.168.0.0/16")
        result = parser.parse_message(bmp)
        body = result["body"]
        assert "192.168.0.0/16" in body.withdrawn_prefixes
        assert body.nlri_prefixes == []

    def test_parse_as_path(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001, as_path=[65001, 65002])
        result = parser.parse_message(bmp)
        assert result["body"].path_attributes["as_path"] == [65001, 65002]

    def test_parse_next_hop(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001, next_hop="192.168.1.1")
        result = parser.parse_message(bmp)
        assert result["body"].path_attributes["next_hop"] == "192.168.1.1"

    def test_parse_nlri_multiple_prefixes(self, parser):
        # Manually build update with two NLRI entries via generator withdraw+update
        gen = MockBGPTelemetryGenerator()
        bmp = gen.generate_update("10.0.0.0/24", 65001)
        result = parser.parse_message(bmp)
        assert len(result["body"].nlri_prefixes) >= 1

    def test_parse_community(self, parser):
        # Communities not generated by default — verify parser handles empty
        gen = MockBGPTelemetryGenerator()
        bmp = gen.generate_update("10.0.0.0/24", 65001)
        result = parser.parse_message(bmp)
        assert "community" not in result["body"].path_attributes or isinstance(
            result["body"].path_attributes.get("community", []), list
        )


class TestBMPParserRoundTrip:
    def test_update_roundtrip(self, gen, parser):
        bmp = gen.generate_update("10.0.0.0/24", 65001, as_path=[65001, 65002, 65003])
        result = parser.parse_message(bmp)
        assert "10.0.0.0/24" in result["body"].nlri_prefixes
        assert result["body"].path_attributes["as_path"] == [65001, 65002, 65003]

    def test_withdraw_roundtrip(self, gen, parser):
        bmp = gen.generate_withdraw("10.0.0.0/24", 65001)
        result = parser.parse_message(bmp)
        assert "10.0.0.0/24" in result["body"].withdrawn_prefixes
